### ISSUE TITLE
Suggest: cite paper

### ISSUE THREAD

**Issue by richelbilderbeek** [kausmees/GenoCAE#1]
Hi  @kausmees,

GCAE seems awesome to me! What I feel is missing is a reference to the paper at BioRxiv. I suggest to add it add it as reference, something like I do below. Sure, I volunteer to do so myself via a Pull Request :-)

## References

 * [1] Ausmees, Kristiina, and Carl Nettelblad. "A deep learning framework for characterization of genotype data." bioRxiv (2020). [here](https://www.biorxiv.org/content/10.1101/2020.09.30.320994v1.abstract)

**Comment by kausmees** [comment]
Good suggestion, go ahead. Just a note on the author list: it should be "Ausmees, Kristiina and Nettelblad, Carl"

**Comment by richelbilderbeek** [comment]
FYI, I just copied Google Scholar:

![Screenshot from 2021-06-10 13-36-11](https://user-images.githubusercontent.com/2098230/121518495-d6528b80-c9f0-11eb-8b08-322a93a61d9c.png)
