### ISSUE TITLE
Suggest + volunteer: rename HumanOrigins249_tiny.snp to HumanOrigins249_tiny.bim

### ISSUE THREAD

**Issue by richelbilderbeek** [kausmees/GenoCAE#11]
Dear GenoCAE maintainer,

Thanks so much for having example files and example code: I find those very useful!

I did find something unexpected, the file extension of `HumanOrigins249_tiny.snp`: this appears to be a PLINK `.bim` file, as it follows the same structure as described [in the PLINK .bim file format doc](https://www.cog-genomics.org/plink2/formats#bim):

![Screenshot from 2021-06-29 11-44-56](https://user-images.githubusercontent.com/2098230/123776304-77858100-d8cf-11eb-9601-42572e44eb55.png)

I suggest to rename the file to what any PLINK user would expect for a `.bim` file, which is `HumanOrigins249_tiny.bim`

I volunteer to do so.

**Comment by kausmees** [comment]
According to the PLINK file format doc, the first field should be the chromosome and the second the variant identifier.
In the .snp file, the order of the two first fields is reversed, so the structure is not the same. In the table in the leftmost image you posted, the data of "chr" and "id" is mismatched.

The example given is in the EIGENSTRAT format, which comprises 3 files (.eigenstratgeno/.snp/.ind).
GCAE also accepts PLINK format (.bed/.bim/.fam).

It might be useful to have the example in PLINK format also, however. If you would like to add that, I'd be happy to accept the pull request.

**Comment by richelbilderbeek** [comment]
> According to the PLINK file format doc, the first field should be the chromosome and the second the variant identifier.

Blimey, you are right! It simply looked too similar too me :-)

> It might be useful to have the example in PLINK format also, however. If you would like to add that, I'd be happy to accept the pull request.

Awesome, I will! At least, I will try, as I have never worked with EIGENSTRAT :+1:

**Comment by richelbilderbeek** [comment]
May be fixed with Pull Request #15

**Comment by richelbilderbeek** [comment]
Hmm, @kausmees, this was harder for me to do than expected and I spent two hours on this. Would it be easy for you to do? If yes, I hope you do this conversion :-), if not, I'll persist :sunglasses:
