### ISSUE TITLE
Suggest + volunteer: text files are not executable

### ISSUE THREAD

**Issue by richelbilderbeek** [kausmees/GenoCAE#12]
Dear GenoCAE maintainers,

Thanks for the example code and examples, I find these very useful!

What is unexpected, however, is that somehow the genetic input files in the folder `example_tiny` are set to be executables, as can be seen in the screenshot of my terminal (see below, green indicates an executable) and by the File Manager asking me to run a text file when I open it (see below, at the right-hand side):

![Screenshot from 2021-06-29 11-52-12](https://user-images.githubusercontent.com/2098230/123777416-79037900-d8d0-11eb-8fb8-38cecde2d725.png)

I guess a `chmod +x` was messed up somewhere :-)

I suggest to remove the executable flag of these simple text files. 

I volunteer to do so.

**Comment by kausmees** [comment]
This is indeed very stange, please do remove the executable flag.

Thanks!

**Comment by richelbilderbeek** [comment]
Cool, will do so!

(BTW, I suggest to keep the Issue open as long as it is not fixed or rejected)

**Comment by richelbilderbeek** [comment]
Pull Request at #14 :-)

**Comment by richelbilderbeek** [comment]
Screenshot to prove that works:

![Screenshot from 2021-06-29 12-46-58](https://user-images.githubusercontent.com/2098230/123784802-1b732a80-d8d8-11eb-8d8d-11555d814da8.png)
