### ISSUE TITLE
Use 'project' without a 'HO_superpopulation' file

### ISSUE THREAD

**Issue by richelbilderbeek** [kausmees/GenoCAE#23]
This is a note to self, as I cannot assign myself as I am not a Collaborator. Hence I assign myself in text :-)

**Comment by richelbilderbeek** [comment]
I #22 Kristiina stated that one can use use `project` without the `HO_superpopulation` file. To be able to continue on my work, I work on getting the `project` to work without that file. All that will be lacking is the colors ... :-)

**Comment by kausmees** [comment]
The current version of the code should give every population a unique color if no superpops argument is given, the only difference will be that the colors wont be "grouped" so pops within the same superpop have similar colors. Its been tested for the example data given (although I remember there may be some issues with the formatting of the legend), let me know if it doesnt work for your data.

**Comment by richelbilderbeek** [comment]
Works:

```
python3 run_gcae.py project --datadir example_tiny --data issue_6_bin --model_id M1 --train_opts_id ex3 --data_opts_id b_0_4 --pheno_model_id=p1
```
results in:

```
saving plot to /home/richel/GitHubs/GenoCAE/ae_out/ae.M1.ex3.b_0_4.issue_6_bin.p1/issue_6_bin/dimred_e_3.pdf
```

[dimred_e_3.pdf](https://github.com/kausmees/GenoCAE/files/7676210/dimred_e_3.pdf)
