### ISSUE TITLE
Suggest + volunteer: add GitHub Actions continuous integration

### ISSUE THREAD

**Issue by richelbilderbeek** [kausmees/GenoCAE#4]
Continuous integration is the workflow in which after every -among others- `git push`, the project is tested to 'still work'. Not only is this helpful to speed up development, it also allows one to see if code from contributors (via a Pull Request) keep the build intact.

I suggest to add a minimal GitHub Actions script that simply does the steps in the README.md.

I volunteer to write it and maintain it, as I have plenty of experience with that (e.g. [plinkr](https://github.com/richelbilderbeek/plinkr), but there are dozens if not hundreds)

Good idea?

**Comment by richelbilderbeek** [comment]
BTW, you can already see the GCAE help at [the GHA script on my Fork](https://github.com/richelbilderbeek/GenoCAE/runs/2894086506?check_suite_focus=true#step:7:1).

**Comment by kausmees** [comment]
Thanks, fixed in c5a55c0.
