### ISSUE TITLE
Suggest: release a version

### ISSUE THREAD

**Issue by richelbilderbeek** [kausmees/GenoCAE#6]
Dear GenoCAE maintainers,

I quote from [the GitHub docs](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases):

> Releases are deployable software iterations you can package and make available for a wider audience to download and use.

I would love to have a named release version, e.g. `v1.0` ([as that is the version shown in the help](https://github.com/kausmees/GenoCAE/blob/master/run_gcae.py#L364)) that I can use (over the commit hash) for [the gcaer R package](https://github.com/richelbilderbeek/gcaer) I am writing to install this cool tool.

It's easy to make one: 

![there](https://user-images.githubusercontent.com/2098230/123195377-5aece180-d4a8-11eb-8bd2-5b599e9e790d.png)

Sure, I volunteer to do this, but for that I need more access rights than you may want to give (which I'd understand :-) ).

**Comment by kausmees** [comment]
Thanks for the suggestion, release v1.0 has just been published.
